"""The generated documents, and the check that they are current.

    twinflow-roadmap render            write every generated document
    twinflow-roadmap render --check    regenerate in memory and diff

docs/gates.md is the readable projection of gates.yaml, the way ROADMAP.md is
the readable projection of roadmap.yaml. It is generated for the reason every
generated artifact here is generated: a hand-maintained second copy of the gate
registry drifts, and the drift is invisible until somebody reads both.

--check is what step 8 of the release ritual runs. It regenerates in memory and
compares, so a tag can never carry a gate table that disagrees with the registry
the gates actually run from.

WHY ROADMAP.md IS NOT WHOLLY GENERATED
---------------------------------------
ROADMAP.md section 3's phase table and section 7's gate tables are projections
of the data, and its ordering arguments, doctrine rulings, and resequencing
register are prose nobody can generate. So the file stays hand-maintained and
two checks hold it to the data instead: `graph-lint` re-parses its phase diagram
against roadmap.yaml, and the gate table below is published as its own document
rather than spliced into the middle of an argument.
"""

from __future__ import annotations

import difflib
from pathlib import Path

from twinflow_roadmap.errors import Finding
from twinflow_roadmap.roadmap import Roadmap

GATES_DOC = Path("docs") / "gates.md"

#: The description is one line in the rendered file and two here, because ruff
#: caps a source line at 100 characters and the front matter field cannot wrap.
_DESCRIPTION = (
    "Every gate this project runs, its phase, its kind, what it asserts, and what "
    "falsifies it, generated from gates.yaml."
)

HEADER = f"""---
title: Validation gates
description: {_DESCRIPTION}
topic_type: reference
audience: contributors
---

<!-- GENERATED by `just roadmap render` from gates.yaml. Do not edit by hand. -->

# Validation gates

Every gate this project runs, as `gates.yaml` declares it. A gate is declared at
Phase 0 with the phase it starts at, so a subsystem has to specify its gates one
phase ahead of implementing them, and `roadmap validate` fails a work package in
the open phase that references a gate still at status `declared`.

Three statuses, and the required field set widens with each:

| Status        | Owes                                                            |
|---------------|-----------------------------------------------------------------|
| `declared`    | a unique id, a first phase, and a standing flag                 |
| `specified`   | plus an assertion, what falsifies it, and its kind's fields     |
| `implemented` | plus a test on disk and the command the phase-exit runner calls |

`just gate phase-exit <phase>` runs every gate in force at a phase. A gate in
that set which is not `implemented` fails the run rather than being skipped,
because the registry already promised it at the phase it starts at.
"""


def table(header: list[str], rows: list[list[str]]) -> list[str]:
    """A markdown table with its pipes aligned.

    Aligned because .markdownlint.jsonc asks for it, and a generator that emits
    markdown its own lint refuses is a generator whose output nobody can commit.
    """
    widths = [len(cell) for cell in header]
    for row in rows:
        widths = [max(width, len(cell)) for width, cell in zip(widths, row, strict=True)]

    def line(cells: list[str]) -> str:
        padded = (cell.ljust(width) for cell, width in zip(cells, widths, strict=True))
        return "| " + " | ".join(padded) + " |"

    return [
        line(header),
        "|" + "|".join("-" * (width + 2) for width in widths) + "|",
        *(line(row) for row in rows),
    ]


def render_gates(roadmap: Roadmap) -> str:
    """docs/gates.md, as the registry describes it."""
    lines = [HEADER.strip(), "", f"## The registry ({len(roadmap.gates)} gates)", ""]
    lines += table(
        ["Gate", "First phase", "Kind", "Standing", "Status", "Owner"],
        [
            [
                f"`{gate_id}`",
                roadmap.gates[gate_id].first_phase,
                roadmap.gates[gate_id].kind,
                "yes" if roadmap.gates[gate_id].standing else "no",
                roadmap.gates[gate_id].status,
                roadmap.gates[gate_id].owner_section,
            ]
            for gate_id in sorted(roadmap.gates)
        ],
    )

    lines += ["", "## What each gate asserts", ""]
    for gate_id in sorted(roadmap.gates):
        gate = roadmap.gates[gate_id]
        lines.append(f"### `{gate_id}`")
        lines.append("")
        if gate.status == "declared":
            lines += [
                f"Declared at {gate.first_phase}, owned by {gate.owner_section}. Its assertion "
                f"is specified one phase before it is implemented, which is what stops a gate "
                f"being written to fit the code that was going to be written anyway.",
                "",
            ]
            continue
        lines += [f"**Asserts.** {(gate.assertion or '').strip()}", ""]
        lines += [f"**Falsified by.** {(gate.falsified_by or '').strip()}", ""]
        if gate.reference:
            reference = gate.reference.strip()
            if gate.reference_url:
                reference = f"{reference} <{gate.reference_url}>"
            lines += [f"**Reference.** {reference}", ""]
        if gate.truth_source:
            lines += [f"**Truth source.** {gate.truth_source.strip()}", ""]
        if gate.null_model:
            lines += [f"**Null model.** {gate.null_model.strip()}", ""]
        if gate.noise_floor:
            lines += [f"**Noise floor.** {gate.noise_floor.strip()}", ""]
        if gate.status == "implemented":
            tested = ", ".join(f"`{path}`" for path in gate.test_paths())
            lines += [f"**Runs.** `{gate.command}`, tested by {tested}.", ""]

    lines += [
        "## Exit sets by phase",
        "",
        "Derived from the registry: every gate whose first phase is this one, plus every",
        "standing gate already in force. Never authored, so the phase table and the",
        "registry cannot disagree.",
        "",
    ]
    lines += table(
        ["Phase", "Gates in force"],
        [[f"`{phase.id}`", str(len(roadmap.exit_gates(phase.id)))] for phase in roadmap.phases],
    )

    return "\n".join(lines) + "\n"


#: Every generated document, and the function that produces it.
DOCUMENTS = {GATES_DOC: render_gates}


def check(roadmap: Roadmap) -> list[Finding]:
    """Every generated document that is not what its generator produces now."""
    findings: list[Finding] = []
    for relative, generator in DOCUMENTS.items():
        path = roadmap.root / relative
        expected = generator(roadmap)
        actual = path.read_text(encoding="utf-8") if path.is_file() else ""
        if actual == expected:
            continue
        diff = list(
            difflib.unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile=f"{relative} on disk",
                tofile=f"{relative} regenerated",
                lineterm="",
                n=1,
            )
        )
        preview = "; ".join(line for line in diff[2:8] if line.strip())
        findings.append(
            Finding(
                "RENDER-STALE",
                f"{relative.as_posix()} is not what its generator produces. Run "
                f"`just roadmap render`. First difference: {preview[:200]}",
                relative.as_posix(),
            )
        )
    return findings


def write(roadmap: Roadmap) -> list[Path]:
    """Write every generated document, and return the ones that changed."""
    changed: list[Path] = []
    for relative, generator in DOCUMENTS.items():
        path = roadmap.root / relative
        expected = generator(roadmap)
        if path.is_file() and path.read_text(encoding="utf-8") == expected:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n" rather than the platform default. This file is compared
        # byte for byte by --check, and a Windows checkout writing CRLF would
        # make the release ritual fail on a difference nobody made.
        path.write_text(expected, encoding="utf-8", newline="\n")
        changed.append(relative)
    return changed
