"""The published registry (C3) and the differ behind gate SCH-001.

The published schema and the model are one definition here, generated one from
the other, so these tests check the things generation cannot: that the published
file really accepts what the model accepts and rejects what it rejects, and that
the differ implements the compatibility table rather than approximating it.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema
import pytest
import yaml
from pydantic import ValidationError

from twinflow.schemas import Envelope, compare_schemas

REPO_ROOT = Path(__file__).resolve().parents[3]
SCHEMAS_DIR = REPO_ROOT / "schemas"
ENVELOPE_SCHEMA = SCHEMAS_DIR / "envelope" / "v1.json"


def _schema() -> dict:
    return json.loads(ENVELOPE_SCHEMA.read_text(encoding="utf-8"))


def _valid_event() -> dict:
    return {
        "specversion": "1.0",
        "id": "01J0000000000000000000000A",
        "source": "/twinflow/sim/receiving",
        "type": "twinflow.twin.pallet_scanned",
        "time": "2026-08-09T00:00:00Z",
        "datacontenttype": "application/json",
        "dataschema": "twinflow:schemas/twin/pallet_scanned/v1.0.json",
        "twinflowsimts": "0",
        "twinflowrunid": "run_01J0000000000000000000000A",
        "twinflowproducerid": "sim",
        "twinflowseq": "0",
        "data": {},
    }


def test_the_published_schema_declares_the_dialect_the_registry_names():
    registry = yaml.safe_load((SCHEMAS_DIR / "registry.yaml").read_text(encoding="utf-8"))
    assert _schema()["$schema"] == registry["dialect"]


def test_the_registry_lists_every_published_file():
    """A schema on disk that no manifest names is a subject nobody declared."""
    registry = yaml.safe_load((SCHEMAS_DIR / "registry.yaml").read_text(encoding="utf-8"))
    listed = {
        version["file"]
        for subject in registry["subjects"].values()
        for version in subject["versions"]
    }
    on_disk = {
        str(path.relative_to(SCHEMAS_DIR)).replace("\\", "/")
        for path in SCHEMAS_DIR.rglob("*.json")
    }
    assert on_disk == listed


def test_the_published_schema_is_itself_valid_against_its_dialect():
    """The meta-schema check VAL-GATE-CFG-001 asks for, applied here too."""
    schema = _schema()
    validator = jsonschema.validators.validator_for(schema)
    validator.check_schema(schema)


def test_the_published_schema_accepts_what_the_model_accepts():
    event = _valid_event()
    Envelope(**event)
    jsonschema.validate(event, _schema())


@pytest.mark.parametrize(
    "field,bad_value",
    [
        ("twinflowseq", "01"),
        ("twinflowsimts", "12.5"),
        ("twinflowproducerid", "sim-0"),
        ("source", "twinflow/sim/receiving"),
    ],
)
def test_the_published_schema_rejects_what_the_model_rejects(field, bad_value):
    """The drift that matters: a schema looser than its model.

    A constraint held in a field_validator never reaches the generated file, so
    a consumer validating against the published schema would accept an event the
    producer would have refused. Each case here is checked against both.
    """
    event = _valid_event()
    event[field] = bad_value

    with pytest.raises(ValidationError):
        Envelope(**event)

    with pytest.raises(jsonschema.ValidationError):
        jsonschema.validate(event, _schema())


def test_the_published_schema_forbids_an_unknown_attribute():
    event = _valid_event()
    event["twinflowproducer"] = "sim"
    with pytest.raises(jsonschema.ValidationError):
        jsonschema.validate(event, _schema())


def test_no_field_is_marked_as_carrying_personal_data():
    """Every value in this repository is generated by the project itself."""
    assert _schema()["x-twinflow-pii"] is False


# --- the differ, one case per row of the section 5.5 table -------------------


def _schema_with(props: dict, required: list[str] | None = None) -> dict:
    return {"type": "object", "properties": props, "required": required or []}


def test_adding_an_optional_property_with_a_default_is_allowed():
    old = _schema_with({"a": {"type": "string"}})
    new = _schema_with({"a": {"type": "string"}, "b": {"type": "string", "default": ""}})
    assert compare_schemas(old, new) == []


def test_adding_a_required_property_is_rejected():
    old = _schema_with({"a": {"type": "string"}})
    new = _schema_with({"a": {"type": "string"}, "b": {"type": "string"}}, required=["b"])
    assert any("added as required" in f for f in compare_schemas(old, new))


def test_removing_a_property_is_rejected():
    old = _schema_with({"a": {"type": "string"}, "b": {"type": "string"}})
    new = _schema_with({"a": {"type": "string"}})
    assert any("removed" in f for f in compare_schemas(old, new))


def test_making_a_required_property_optional_is_rejected():
    """It loosens the producer and breaks every consumer that assumed presence."""
    old = _schema_with({"a": {"type": "string"}}, required=["a"])
    new = _schema_with({"a": {"type": "string"}}, required=[])
    assert any("now optional" in f for f in compare_schemas(old, new))


def test_making_an_optional_property_required_is_rejected():
    """The row the unit cases missed until an end-to-end run found it.

    Every existing producer publishes events without the field, and a schema
    that now requires it rejects all of them.
    """
    old = _schema_with({"a": {"type": "string"}}, required=[])
    new = _schema_with({"a": {"type": "string"}}, required=["a"])
    assert any("now required" in f for f in compare_schemas(old, new))


def test_changing_a_type_is_rejected():
    old = _schema_with({"a": {"type": "string"}})
    new = _schema_with({"a": {"type": "integer"}})
    assert any("type changed" in f for f in compare_schemas(old, new))


def test_narrowing_a_range_is_rejected():
    old = _schema_with({"a": {"type": "number", "minimum": 0, "maximum": 10}})
    new = _schema_with({"a": {"type": "number", "minimum": 2, "maximum": 10}})
    assert any("narrowed" in f for f in compare_schemas(old, new))


def test_widening_a_closed_range_is_rejected():
    """The rule that is easy to get wrong, and the reason the keyword exists."""
    old = _schema_with({"a": {"type": "number", "minimum": 0, "maximum": 1}})
    new = _schema_with({"a": {"type": "number", "minimum": 0, "maximum": 2}})
    assert any("widened" in f for f in compare_schemas(old, new))


def test_widening_an_open_range_is_allowed():
    old = _schema_with(
        {"a": {"type": "number", "minimum": 0, "maximum": 1, "x-twinflow-open-range": True}}
    )
    new = _schema_with(
        {"a": {"type": "number", "minimum": 0, "maximum": 2, "x-twinflow-open-range": True}}
    )
    assert compare_schemas(old, new) == []


def test_adding_an_enum_member_is_rejected_on_a_closed_enum():
    old = _schema_with({"a": {"type": "string", "enum": ["x"]}})
    new = _schema_with({"a": {"type": "string", "enum": ["x", "y"]}})
    assert any("enum members added" in f for f in compare_schemas(old, new))


def test_adding_an_enum_member_is_allowed_on_an_open_enum():
    old = _schema_with({"a": {"type": "string", "enum": ["x"], "x-twinflow-open-enum": True}})
    new = _schema_with({"a": {"type": "string", "enum": ["x", "y"], "x-twinflow-open-enum": True}})
    assert compare_schemas(old, new) == []


def test_removing_an_enum_member_is_rejected_even_when_open():
    old = _schema_with({"a": {"type": "string", "enum": ["x", "y"], "x-twinflow-open-enum": True}})
    new = _schema_with({"a": {"type": "string", "enum": ["x"], "x-twinflow-open-enum": True}})
    assert any("enum members removed" in f for f in compare_schemas(old, new))


def test_renaming_a_property_reads_as_a_removal_and_an_addition():
    old = _schema_with({"a": {"type": "string"}})
    new = _schema_with({"b": {"type": "string", "default": ""}})
    findings = compare_schemas(old, new)
    assert any("removed" in f for f in findings)


def test_the_envelope_is_compatible_with_itself():
    """The trivial case, which a differ that reports everything would fail."""
    assert compare_schemas(_schema(), _schema()) == []
