"""Generate .importlinter from the layer table in the root pyproject.toml.

    uv run python tools/gen_importlinter.py            write .importlinter
    uv run python tools/gen_importlinter.py --check    regenerate and diff

Boundary rule A1.3 says the layer list and the domain-package list are read
from `[tool.twinflow.layers]`, so the contract and the gate cannot disagree
(D-09). A hand-written .importlinter would be a second copy of that list, and a
second copy is a copy that drifts. This generates the first from the second and
the check mode fails when they part company.

Only packages that exist under packages/ reach the generated file. import-linter
resolves every module it is given, so naming a package the roadmap has not built
yet would fail the contract on a module nobody wrote.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ROOT_PYPROJECT = REPO_ROOT / "pyproject.toml"
PACKAGES_DIR = REPO_ROOT / "packages"
CONFIG = REPO_ROOT / ".importlinter"

HEADER = """\
# GENERATED by tools/gen_importlinter.py from [tool.twinflow.layers] in
# pyproject.toml. Do not edit by hand: run the generator instead, and the
# --check mode in CI fails when this file and that table disagree.
#
# Boundary rules A1.1 through A1.3 of docs/design/foundations.md section 2.9.
"""


def existing_packages() -> set[str]:
    """The twinflow.<name> subpackages that actually exist in this workspace."""
    found = set()
    if not PACKAGES_DIR.is_dir():
        return found
    for package_dir in sorted(PACKAGES_DIR.iterdir()):
        src = package_dir / "src" / "twinflow"
        if not src.is_dir():
            continue
        for module in sorted(src.iterdir()):
            if module.is_dir() and (module / "__init__.py").is_file():
                found.add(module.name)
    return found


def render(layers: dict, present: set[str]) -> str:
    order = layers["order"]
    lines = [HEADER, "", "[importlinter]", "root_packages =", "    twinflow", ""]

    # A1.3, the layering contract. Each tier is one layer line; siblings inside
    # a tier are separated by a pipe, which is how import-linter spells "these
    # are peers, and none of them may import another".
    tiers = []
    for tier in order:
        members = [f"twinflow.{name}" for name in layers[tier] if name in present]
        if members:
            tiers.append(" | ".join(members))
    if tiers:
        lines += [
            "[importlinter:contract:layers]",
            "name = A1.3 layering, apps down to schemas",
            "type = layers",
            "layers =",
        ]
        lines += [f"    {tier}" for tier in tiers]
        lines.append("")

    # A1.2, sibling domain packages do not import each other at all. They talk
    # through kernel ports and versioned events.
    domain = [f"twinflow.{name}" for name in layers["domain"] if name in present]
    if len(domain) > 1:
        lines += [
            "[importlinter:contract:domain-independence]",
            "name = A1.2 domain packages are independent",
            "type = independence",
            "modules =",
        ]
        lines += [f"    {module}" for module in domain]
        lines.append("")

    # A1.1, no package imports another package's private subpackage. One
    # contract per package, because the forbidden set differs for each: a
    # package may of course import its own _impl.
    all_present = sorted(present)
    for owner in all_present:
        others = [f"twinflow.{name}" for name in all_present if name != owner]
        if not others:
            continue
        lines += [
            f"[importlinter:contract:private-{owner}]",
            f"name = A1.1 twinflow.{owner} private modules stay private",
            "type = forbidden",
            "source_modules =",
        ]
        lines += [f"    {module}" for module in others]
        lines += [
            "forbidden_modules =",
            f"    twinflow.{owner}._impl",
            f"    twinflow.{owner}._internal",
            # A1.1 forbids reaching into another package's private modules. It
            # does not forbid importing that package. Without this, every
            # consumer of a package whose __init__ re-exports from its own
            # _impl is reported as a violation, because import-linter follows
            # the chain `consumer -> twinflow.owner -> twinflow.owner._impl`
            # and reports the private module at the end of it. That chain is
            # the design: _impl is private precisely so the public module is
            # the only way in. The rule that matters is the direct import,
            # which this still catches.
            "allow_indirect_imports = True",
            "",
        ]

    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail when it differs from the file",
    )
    args = parser.parse_args()

    root = tomllib.loads(ROOT_PYPROJECT.read_text(encoding="utf-8"))
    layers = root.get("tool", {}).get("twinflow", {}).get("layers")
    if not layers:
        sys.stderr.write("no [tool.twinflow.layers] in pyproject.toml\n")
        return 1

    rendered = render(layers, existing_packages())

    if args.check:
        if not CONFIG.is_file():
            sys.stderr.write(f"missing {CONFIG}; run tools/gen_importlinter.py\n")
            return 1
        if CONFIG.read_text(encoding="utf-8") != rendered:
            sys.stderr.write(
                f"{CONFIG} does not match [tool.twinflow.layers]. "
                "Run: uv run python tools/gen_importlinter.py\n"
            )
            return 1
        print(f"{CONFIG} matches the layer table")
        return 0

    CONFIG.write_text(rendered, encoding="utf-8")
    print(f"wrote {CONFIG}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
