"""Generate the published JSON Schema files under schemas/ from their models.

    uv run python tools/gen_schemas.py            write the schema files
    uv run python tools/gen_schemas.py --check    regenerate in memory and diff

schemas/ is the language-neutral registry: the Rust device agent and every
external consumer read it, and nothing there imports Python. That is exactly why
it is generated rather than hand-written. A hand-maintained second definition of
the envelope would drift from the model, and the drift would be silent until a
consumer accepted an event the producer would have rejected.

Generating also means a constraint has to be declarative on the model to reach
the published file. A rule hidden in a field_validator produces a schema that is
weaker than the model, which is worse than no schema: it says the contract is
looser than it is.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from twinflow.schemas import Envelope

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMAS_DIR = REPO_ROOT / "schemas"

#: JSON Schema 2020-12, which foundations 5.5 fixes for the whole registry.
DIALECT = "https://json-schema.org/draft/2020-12/schema"

#: Custom annotation keywords are documented in schemas/x-keywords.md. Only the
#: ones that apply to the envelope appear here.
SUBJECTS: dict[str, dict] = {
    "envelope/v1": {
        "model": Envelope,
        "id": "twinflow:schemas/envelope/v1.json",
        "title": "twinflow event envelope",
        "description": (
            "The CloudEvents 1.0.2 envelope every twinflow event carries. "
            "Settled in P0 before any subject schema publishes, because adding "
            "a field afterwards is a major version bump on every subject."
        ),
        "extra_keywords": {
            # No field in this repository carries personal data: every value is
            # generated by the project itself. Asserted by a test rather than
            # left as a claim.
            "x-twinflow-pii": False,
            # The historian partitions on the run, so a replay reads one run
            # without scanning the rest.
            "x-twinflow-partition-key": "twinflowrunid",
            "x-twinflow-since": "0.1.0",
        },
    }
}


def build(subject: str) -> dict:
    spec = SUBJECTS[subject]
    schema = spec["model"].model_json_schema()

    # Pydantic emits titles derived from field names, which carry no information
    # a reader of the published file does not already have from the key. They
    # are dropped so a diff between two versions shows real changes only.
    schema.pop("title", None)
    for prop in schema.get("properties", {}).values():
        prop.pop("title", None)

    ordered = {
        "$schema": DIALECT,
        "$id": spec["id"],
        "title": spec["title"],
        "description": spec["description"],
        **spec["extra_keywords"],
    }
    ordered.update(schema)
    return ordered


def render(schema: dict) -> str:
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail when a file differs",
    )
    args = parser.parse_args()

    drifted: list[str] = []
    for subject in sorted(SUBJECTS):
        path = SCHEMAS_DIR / f"{subject}.json"
        rendered = render(build(subject))

        if args.check:
            if not path.is_file():
                drifted.append(f"{path} is missing")
            elif path.read_text(encoding="utf-8") != rendered:
                drifted.append(f"{path} differs from a fresh generation")
            continue

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")
        print(f"wrote {path}")

    if args.check:
        if drifted:
            for line in drifted:
                print(line, file=sys.stderr)
            print(
                "\nRun: uv run python tools/gen_schemas.py\n"
                "A published schema that disagrees with its model is a contract "
                "nobody is holding to.",
                file=sys.stderr,
            )
            return 1
        print(f"{len(SUBJECTS)} published schemas match their models")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
